Feat/adjust cosmos toolbox
thorswap/SwapKit pull request #1043
Opened 2024-10-16 13:49 UTC by alexisshleverx

2024-10-17 12:39 UTC, ice-chillios requested changes

2024-10-17 12:39 UTC, ice-chillios commented on packages/toolboxes/cosmos/src/toolbox/thorchain.ts
> +    buildTransferTx: _buildTransferTx,
Instead of inline declaration - please use currying as `buildDepositTx` and `buildTransferTx`:
```ts
buildDepositTx: buildDepositTx(rpcUrl)
```

2024-10-17 12:39 UTC, ice-chillios commented on packages/toolboxes/cosmos/src/toolbox/gaia.ts
> +import { type GaiaToolboxType, type ToolboxParams, buildNativeTransferTx } from "../index";
that import produces `cycle requires` please import them directly - not from re-export

2024-10-17 12:39 UTC, ice-chillios commented on packages/toolboxes/cosmos/src/toolbox/BaseCosmosToolbox.ts
> +}) => {
That shouldn't be changed - it seems like your editor doesn't respect `biome` config. Please check out

2024-10-17 12:39 UTC, ice-chillios commented on packages/toolboxes/cosmos/src/thorchainUtils/messages.ts
> +    throw new Error("Account does not exist");
Use `SwapKitError` instead of base Error

2024-10-17 14:11 UTC, ice-chillios reviewed
@alexisshleverx Last but not least ^^

Add changeset file via `bun changeset`

2024-10-18 10:32 UTC, ice-chillios approved these changes

2024-10-22 13:08 UTC, towanTG commented on .changeset/cuddly-weeks-shake.md
> +"@swapkit/plugin-chainflip": patch
you dont need to bump that - but it does not hurt rn

2024-10-22 13:08 UTC, towanTG commented on .changeset/cuddly-weeks-shake.md
> +"@swapkit/wallet-ledger": patch
keepkey-extension bump is missing

2024-10-22 13:51 UTC, alexisshleverx commented on .changeset/cuddly-weeks-shake.md
> +"@swapkit/wallet-ledger": patch
added

2024-10-22 19:11 UTC, merged