feat: trezor wallet
thorswap/SwapKit pull request #61
Opened 2023-04-26 18:09 UTC by towanTG

closes #33

2023-04-26 18:33 UTC, chillios-ts requested changes

2023-04-26 18:33 UTC, chillios-ts commented on apps/vite-playground/src/WalletPicker.tsx
> +          await skClient.connectTrezor(chains, [...NetworkDerivationPath[chains[0]]]);
```suggestion
          await skClient.connectTrezor(chains, NetworkDerivationPath[chains[0]]);
```

2023-04-26 18:33 UTC, chillios-ts commented on apps/vite-playground/vite.config.ts
> +      stream: 'rollup-plugin-node-polyfills/polyfills/stream',
✂️

2023-04-26 18:33 UTC, chillios-ts commented on apps/vite-playground/vite.config.ts
> +  },
✂️

2023-04-26 18:33 UTC, chillios-ts commented on apps/vite-playground/package.json
> +    "rollup-plugin-node-polyfills": "^0.2.1",
✂️

2023-04-26 18:33 UTC, chillios-ts commented on packages/trezor/package.json
> +    "bitcoinjs-lib": "5.2.0"
```suggestion
    "@thorswap-lib/helpers": "workspace:*",
    "@thorswap-lib/swapkit-entities": "workspace:*",
    "@thorswap-lib/types": "workspace:*",
    "@trezor/connect-web": "9.0.7",
```

Those should be placed in devDependencies & peerDependencies, and be included on toolbox (bitcoinjs-lib and @ethers packages should be there already)

2023-04-26 18:33 UTC, chillios-ts commented on packages/trezor/src/signer/evm.ts
> +    debugger;
✂️

2023-04-26 18:33 UTC, chillios-ts commented on packages/trezor/src/signer/evm.ts
> +    //@ts-ignore
it's better to use `@ts-expect-error` instead if possible

2023-04-26 18:33 UTC, chillios-ts commented on packages/trezor/src/trezor.ts
> +    email: 'towan@thorswap.finance',
😓 probably we should leave it blank? or add thorswap mail? 🤔

2023-04-26 18:33 UTC, chillios-ts commented on packages/trezor/src/trezor.ts
> +      const address = await getAddress();
This feels unnecessary -> we should either extract functions is possible outside of it or just use directly form `TrezorConnect.getAddress` call

2023-04-26 18:34 UTC, towanTG commented on apps/vite-playground/vite.config.ts
> +      stream: 'rollup-plugin-node-polyfills/polyfills/stream',
done

2023-04-26 18:34 UTC, towanTG commented on apps/vite-playground/package.json
> +    "rollup-plugin-node-polyfills": "^0.2.1",
done

2023-04-26 18:52 UTC, towanTG commented on apps/vite-playground/vite.config.ts
> +  },
done

2023-04-27 11:07 UTC, chillios-ts approved these changes

2023-04-27 11:28 UTC, merged