[WIP] Chore/short code refactor
thorswap/SwapKit pull request #731
Opened 2024-04-12 21:34 UTC by towanTG

2024-04-12 21:38 UTC, towanTG commented on packages/swapkit/tokens/fetchTokenLists.ts
> +      `https://dev-api.swapkit.dev/tokens?provider=${provider.toUpperCase()}`,
This will have to change before merge. either api v2 will be supporting all provider or v1 will have to add short codes

2024-04-12 21:39 UTC, towanTG commented on packages/toolboxes/cosmos/src/thorchainUtils/memo.ts
> +export function parseMemo(memo: string): MemoInfo {
whats the idea here @olegpetroveth ? currently this is just throwing errors.

also, what do we need shortestIdentifier for? I think we should not add those into asset value but rather have a helper that matches it into identifier, wdyt?

2024-04-12 21:40 UTC, towanTG commented on packages/swapkit/tokens/src/tokenLists/Thorchain.ts
> -      address: "0xB97EF9EF8734C71904D8002F8B6BC66DD9C48A6E",
@ochhii1337 probably better if we keep current format all caps

2024-05-05 18:43 UTC, chillios-dev requested changes
Need second look as I have few doubts how code is structure. 
Also tests could be done in ~80% of code as they have cases which are repetitive

2024-05-05 18:43 UTC, chillios-dev commented on packages/swapkit/helpers/src/helpers/memo.ts
> +      }`;
That part is definitely `too complex` to be binded as those ternaries. Use more variables and be more descriptive or extract those to functions. by having multiple ternaries - code become unreadable.

2024-05-05 18:43 UTC, chillios-dev commented on packages/swapkit/helpers/src/helpers/memo.ts
> +const parseMemoAction = (action: string): MemoType | undefined => {
If that's comment - why it's not required by type?
```suggestion
// parseMemoAction('=')
// parseMemoAction('SWAP')
// MemoType.SWAP
const parseMemoAction = (action: 'SWAP' | '='): MemoType | undefined => {
```

2024-05-05 18:43 UTC, chillios-dev commented on packages/swapkit/helpers/src/helpers/memo.ts
> +  // If no match is found, return undefined
```suggestion
```
✂️

Do not leave comments which describe exactly what code does

2024-06-20 12:05 UTC, closed without merging